# Build settings
plugins:
  - jemoji
  - jekyll-paginate
  - jekyll-seo-tag

# Site settings
title: "Hwannnn"

email: tprp5950@gmail.com
#blog logo
# blog cover
cover: "/assets/images/blog_cover.jpg"

name: 'Changhwan Sin'
author: 'Changhwan Sin'
author_image: "/assets/images/author.jpg"
logo_image: "/assets/images/sheep_logo_black.jpg"

paginate: 8
collections:
  projects:
    output: true
    permalink: /projects/:path/

url: "http://hwannnn.github.io/" # the base hostname & protocol for your site
baseurl: "/Hblog"
#used to display twitter cards

#fill in disqus shortname to use disqus
disqus: Hwannnn-blog
excerpt_separator: <!--more-->

# social icons and sharing options
social:
#  - icon:	twitter
#    url:	https://twitter.com/furorluna
#    desc: Follow me on twitter
#    share_url: http://twitter.com/share
#    share_title: ?text=
#    share_link: "&amp;url="

#  - icon:   linkedin
#    url:	https://www.linkedin.com/nhome/?trk=
#    desc: Information in Linkedin


#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/Hwannnn
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:


# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

description: > # this means to ignore newlines until "baseurl:"
  CAN MACHINES THINK LIKE HUMANS?

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://hwannnn.github.io" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  hwannnn

# Build settings
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

  # Rouge Highlighter in Kramdown › http://kramdown.gettalong.org/syntax_highlighter/rouge.html
  # span, block element options fall back to global
  syntax_highlighter_opts:
    # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: 'highlight'
    #line_numbers: true # bad idea, spans don't need linenos and would inherit this option

theme: jekyll-theme-hacker
